<a href="https://colab.research.google.com/github/raihany-maker/TUGAS-PDS-RAIHANY/blob/main/Pandas_Raihany.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **PANDAS**

# **Sel 1: Pengenalan Pandas Series & NumPy (#P1 - #P6)**

In [1]:
import pandas as pd
import numpy as np

# #P1: Menampilkan array 1-dimensi
print("--- #P1: Pandas Series ---")
ds = pd.Series([2, 4, 6, 8, 10])
print(ds)

--- #P1: Pandas Series ---
0     2
1     4
2     6
3     8
4    10
dtype: int64

In [2]:
# #P2: Series dari list & numpy dengan indeks kustom
print("\n--- #P2: Series & Indeks Kustom ---")
data = pd.Series(['a', 'b', 'c'])
np1 = np.array(['x', 'y', 'z'])
data_np = pd.Series(np1)
print("Data Series biasa:\n", data)
print("\nData Series dari NumPy:\n", data_np)

data_np = pd.Series(np1, index=[2, 3, 4])
print("\nData Series dengan indeks [2,3,4]:\n", data_np)

--- #P2: Series & Indeks Kustom ---
Data Series biasa:
 0    a
1    b
2    c
dtype: object

Data Series dari NumPy:
 0    x
1    y
2    z
dtype: object

Data Series dengan indeks [2,3,4]:
 2    x
3    y
4    z
dtype: object

In [3]:
# #P3: Operasi aritmatika pada Series
print("\n--- #P3: Operasi Aritmatika ---")
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
print("Penjumlahan (+):\n", ds1 + ds2)
print("\nPengurangan (-):\n", ds1 - ds2)
print("\nPerkalian (*):\n", ds1 * ds2)
print("\nPembagian (/):\n", ds1 / ds2)

--- #P3: Operasi Aritmatika ---
Penjumlahan (+):
 0     3
1     7
2    11
3    15
4    19
dtype: int64

Pengurangan (-):
 0    1
1    1
2    1
3    1
4    1
dtype: int64

Perkalian (*):
 0     2
1    12
2    30
3    56
4    90
dtype: int64

Pembagian (/):
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [4]:
# #P4: Konversi Pandas Series ke Python List
print("\n--- #P4: Konversi Series ke List ---")
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series dan type:")
print(ds)
print(type(ds))

print("\nKonversi Pandas Series ke Python list:")
print(ds.tolist())
print(type(ds.tolist()))

--- #P4: Konversi Series ke List ---
Pandas Series dan type:
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>

Konversi Pandas Series ke Python list:
[2, 4, 6, 8, 10]
<class 'list'>

In [5]:
# #P5: Konversi NumPy array ke Pandas Series
print("\n--- #P5: Convert NumPy Array ke Series ---")
np_array = np.array([0, 20, 30, 40, 50])
print("NumPy array:", np_array)

new_np = pd.Series(np_array)
print("\nKonversi Pandas series:\n", new_np)

--- #P5: Convert NumPy Array ke Series ---
NumPy array: [ 0 20 30 40 50]

Konversi Pandas series:
 0     0
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
# #P6: Generate angka random dengan RandomState
print("\n--- #P6: RandomState ---")
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10, 4, 20))
print(num_series)

--- #P6: RandomState ---
0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64

# **Sel 2: Load Data (#P7)**

In [7]:
# ==========================================
# Sel 2: Load Data Penjualan (#P7)
# ==========================================
import pandas as pd

# #P7.2: Load data langsung dari URL raw GitHub
url = 'https://raw.githubusercontent.com/Alam-A99/Pandas_Latih/main/penjualan.csv'
df = pd.read_csv(url)

print("--- 4 Baris Pertama ---")
display(df.head(4))

print("--- 5 Baris Terakhir ---")
display(df.tail())

--- 4 Baris Pertama ---

      nama  jan  feb  mar  apr
0     Andi  100  135   85   75
1     Budi  200  240  185  160
2  Chandra  300  315  285  190
3     Dudi  250  270  230  200

--- 5 Baris Terakhir ---

     nama  jan  feb  mar  apr
5   Fahri   95  130   75   45
6    Gina  125  175  110   70
7  Herman  130  155  100   85
8  Indara  320  374  300  270
9    Joni  200  220  175  155

# **Sel 3: Ekstrak & Manipulasi DataFrame (#P8 - #P11)**

In [8]:
# #P8: Menampilkan 1 Kolom (Pandas Series)
feb = df["feb"]
print("--- #P8: Kolom Feb (Series) ---")
print(feb.head())

--- #P8: Kolom Feb (Series) ---
0    135
1    240
2    315
3    270
4    195
Name: feb, dtype: int64

In [9]:
# #P9: Menampilkan Lebih dari Satu Kolom (DataFrame - Double Bracket)
print("\n--- #P9: Kolom Feb & Mar (DataFrame) ---")
display(df[['feb', 'mar']].head(3))

--- #P9: Kolom Feb & Mar (DataFrame) ---

   feb  mar
0  135   85
1  240  185
2  315  285

In [11]:
# #P10: Tambah Kolom Teks Berisi Angka
penjual = ['penjual no ' + str(i) for i in range(1, 11)]
df['urutan'] = penjual

In [12]:
# #P11: Ekstraksi Angka dari Teks dengan RegEx
df['no'] = df['urutan'].str.extract(r'(\d+)').astype('int64')

print("\n--- #P10 & #P11: DataFrame Setelah Edit Kolom ---")
display(df)

--- #P10 & #P11: DataFrame Setelah Edit Kolom ---

      nama  jan  feb  mar  apr         urutan  no
0     Andi  100  135   85   75   penjual no 1   1
1     Budi  200  240  185  160   penjual no 2   2
2  Chandra  300  315  285  190   penjual no 3   3
3     Dudi  250  270  230  200   penjual no 4   4
4      Eko  150  195  110  100   penjual no 5   5
5    Fahri   95  130   75   45   penjual no 6   6
6     Gina  125  175  110   70   penjual no 7   7
7   Herman  130  155  100   85   penjual no 8   8
8   Indara  320  374  300  270   penjual no 9   9
9     Joni  200  220  175  155  penjual no 10  10

# **Sel 4: Memilih Data Berdasarkan Baris & Kolom (#P12)**

In [13]:
# #P12.1: Menampilkan baris indeks berlabel 0
print("--- #P12.1: Baris Indeks 0 ---")
print("Via loc  :\n", df.loc[0])
print("\nVia iloc :\n", df.iloc[0])

--- #P12.1: Baris Indeks 0 ---
Via loc  :
 nama              Andi
jan                100
feb                135
mar                 85
apr                 75
urutan    penjual no 1
no                   1
Name: 0, dtype: object

Via iloc :
 nama              Andi
jan                100
feb                135
mar                 85
apr                 75
urutan    penjual no 1
no                   1
Name: 0, dtype: object

In [14]:
# #P12.2: Menampilkan baris 0 dan kolom 'jan'
print("\n--- #P12.2: Baris 0, Kolom 'jan' ---")
print("loc  :", df.loc[0, 'jan'])
print("iloc :", df.iloc[0, 1])
display(df[['jan']][:1])

--- #P12.2: Baris 0, Kolom 'jan' ---
loc  : 100
iloc : 100

   jan
0  100

In [15]:
# #P12.3: Menampilkan subset baris & kolom tertentu
print("\n--- #P12.3: loc 0:2 vs iloc 0:3 ---")
display(df.loc[0:2, ['nama', 'jan', 'mar']])
display(df.iloc[0:3, [0, 1, 3]])

--- #P12.3: loc 0:2 vs iloc 0:3 ---

      nama  jan  mar
0     Andi  100   85
1     Budi  200  185
2  Chandra  300  285

      nama  jan  mar
0     Andi  100   85
1     Budi  200  185
2  Chandra  300  285

In [16]:
# #P12.4: Menampilkan semua baris kolom nama & apr
print("\n--- #P12.4: Semua Baris Kolom nama & apr ---")
display(df.loc[:, ['nama', 'apr']])

--- #P12.4: Semua Baris Kolom nama & apr ---

      nama  apr
0     Andi   75
1     Budi  160
2  Chandra  190
3     Dudi  200
4      Eko  100
5    Fahri   45
6     Gina   70
7   Herman   85
8   Indara  270
9     Joni  155

In [17]:
# #P12.5: Menampilkan semua baris kolom nama sampai feb
print("\n--- #P12.5: Kolom nama Sampai feb ---")
display(df.loc[:, 'nama':'feb'])

--- #P12.5: Kolom nama Sampai feb ---

      nama  jan  feb
0     Andi  100  135
1     Budi  200  240
2  Chandra  300  315
3     Dudi  250  270
4      Eko  150  195
5    Fahri   95  130
6     Gina  125  175
7   Herman  130  155
8   Indara  320  374
9     Joni  200  220

# **Sel 5: Memfilter Data (#P13 - #P14)**

In [18]:
import re

# #P13.2: Filtering Berdasarkan Teks
print("--- Nama mengandung 'Andi' ---")
display(df[df['nama'].str.contains('Andi')])

print("--- Nama mengandung 'in' (Ignore Case) ---")
display(df[df['nama'].str.contains('in', flags=re.IGNORECASE)])

print("--- Feb bernilai 130 dan 220 ---")
feb_penjualan = [130, 220]
display(df[df['feb'].isin(feb_penjualan)])

--- Nama mengandung 'Andi' ---

   nama  jan  feb  mar  apr        urutan  no
0  Andi  100  135   85   75  penjual no 1   1

--- Nama mengandung 'in' (Ignore Case) ---

     nama  jan  feb  mar  apr        urutan  no
6    Gina  125  175  110   70  penjual no 7   7
8  Indara  320  374  300  270  penjual no 9   9

--- Feb bernilai 130 dan 220 ---

    nama  jan  feb  mar  apr         urutan  no
5  Fahri   95  130   75   45   penjual no 6   6
9   Joni  200  220  175  155  penjual no 10  10

In [19]:
# #P13.1: Filtering Berdasarkan Angka (Satu Kondisi)
print("--- Jan == 200 ---")
display(df[df['jan'] == 200])

print("--- Jan > 200 ---")
display(df[df['jan'] > 200])

--- Jan == 200 ---

   nama  jan  feb  mar  apr         urutan  no
1  Budi  200  240  185  160   penjual no 2   2
9  Joni  200  220  175  155  penjual no 10  10

--- Jan > 200 ---

      nama  jan  feb  mar  apr        urutan  no
2  Chandra  300  315  285  190  penjual no 3   3
3     Dudi  250  270  230  200  penjual no 4   4
8   Indara  320  374  300  270  penjual no 9   9

In [20]:
# #P14: Filtering Menggunakan DataFrame Lain & Banyak Kondisi
d = {'tinggi': [320, 300], 'rendah': [95, 100]}
df1 = pd.DataFrame(data=d)

print("--- Jan yang ada di df1['tinggi'] ---")
display(df[df['jan'].isin(df1['tinggi'])])

print("--- Jan yang ada di df1['rendah'] ---")
display(df[df['jan'].isin(df1['rendah'])])

print("--- Jan Antara 100 dan 300 ---")
display(df[(df['jan'] > 100) & (df['jan'] < 300)])

print("--- Nama ada 'on' (Ignore Case) ATAU Jan > 200 ---")
display(df[(df['nama'].str.contains('on', flags=re.IGNORECASE)) | (df['jan'] > 200)])

--- Jan yang ada di df1['tinggi'] ---

      nama  jan  feb  mar  apr        urutan  no
2  Chandra  300  315  285  190  penjual no 3   3
8   Indara  320  374  300  270  penjual no 9   9

--- Jan yang ada di df1['rendah'] ---

    nama  jan  feb  mar  apr        urutan  no
0   Andi  100  135   85   75  penjual no 1   1
5  Fahri   95  130   75   45  penjual no 6   6

--- Jan Antara 100 dan 300 ---

     nama  jan  feb  mar  apr         urutan  no
1    Budi  200  240  185  160   penjual no 2   2
3    Dudi  250  270  230  200   penjual no 4   4
4     Eko  150  195  110  100   penjual no 5   5
6    Gina  125  175  110   70   penjual no 7   7
7  Herman  130  155  100   85   penjual no 8   8
9    Joni  200  220  175  155  penjual no 10  10

--- Nama ada 'on' (Ignore Case) ATAU Jan > 200 ---

      nama  jan  feb  mar  apr         urutan  no
2  Chandra  300  315  285  190   penjual no 3   3
3     Dudi  250  270  230  200   penjual no 4   4
8   Indara  320  374  300  270   penjual no 9   9
9     Joni  200  220  175  155  penjual no 10  10

# **Sel 6: Metode Pandas & Fungsi Apply (#P15)**

In [21]:
# ==========================================
# Sel 6: Ringkasan Statistik & Apply (#P15)
# ==========================================

# Ringkasan statistik DataFrame
print("--- Ringkasan Statistik (df.describe) ---")
display(df.describe())

# #P15: Metode apply untuk fungsi kustom pada Series
print("\n--- #P15: Hasil Fungsi Apply ---")
data = [1, 1, 2, 3, 5, 8, 13, 21]
d_int = pd.Series(data)

def kecilbesar(num):
    if num < 3:
        return "kecil"
    elif num >= 3 and num < 13:
        return "sedang"
    else:
        return "besar"

hasil = d_int.apply(kecilbesar)
print(hasil)

# Informasi struktur DataFrame
print("\n--- Informasi DataFrame (df.info) ---")
df.info()

--- Ringkasan Statistik (df.describe) ---

             jan         feb         mar         apr        no
count   10.00000   10.000000   10.000000   10.000000  10.00000
mean   187.00000  220.900000  165.500000  135.000000   5.50000
std     81.14459   80.161573   83.081285   71.608504   3.02765
min     95.00000  130.000000   75.000000   45.000000   1.00000
25%    126.25000  160.000000  102.500000   77.500000   3.25000
50%    175.00000  207.500000  142.500000  127.500000   5.50000
75%    237.50000  262.500000  218.750000  182.500000   7.75000
max    320.00000  374.000000  300.000000  270.000000  10.00000

--- #P15: Hasil Fungsi Apply ---
0     kecil
1     kecil
2     kecil
3    sedang
4    sedang
5    sedang
6     besar
7     besar
dtype: object

--- Informasi DataFrame (df.info) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nama    10 non-null     object
 1   jan     10 non-null     int64
 2   feb     10 non-null     int64
 3   mar     10 non-null     int64
 4   apr     10 non-null     int64
 5   urutan  10 non-null     object
 6   no      10 non-null     int64
dtypes: int64(5), object(2)
memory usage: 692.0+ bytes